#:schema node_modules/wrangler/config-schema.json
name = "kv-tutorial"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "SPACE"
id = "ed38b6d896864c539855c1d44b80844d"

[observability]
enabled = true